import jsPDF from 'jspdf';

export interface PDFExportData {
  title: string;
  kpis: Record<string, string | number>;
  charts: string[]; // base64 PNG data URLs
  tables: Record<string, { headers: string[]; rows: any[][] }>;
}

export async function exportDashboardToPDF(data: PDFExportData, token: string | null) {
  const useMock = import.meta.env.VITE_USE_MOCK !== 'false';
  
  if (!useMock) {
    // Call secure backend PDF generation endpoint
    const response = await fetch(`${import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'}/reports/export-pdf`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify(data)
    });
    
    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(errorText || `Export failed with status ${response.status}`);
    }
    
    const blob = await response.blob();
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `transitops_report_${new Date().toISOString().slice(0, 10)}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    return;
  }

  // Client-side PDF generation for mock mode
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let currentY = 50;

  // Colors matching design system
  const orangeAccent = '#F59E0B';

  const drawPageDecorations = (pdf: jsPDF, pageNum: number, totalPages: number) => {
    pdf.setFont('Helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(107, 114, 128);
    
    // Header
    pdf.text('Fleet Analytics Report', 54, 30);
    pdf.setStrokeColor(226, 232, 240);
    pdf.setLineWidth(0.5);
    pdf.line(54, 35, pageWidth - 54, 35);

    // Footer
    pdf.line(54, pageHeight - 45, pageWidth - 54, pageHeight - 45);
    pdf.text('Generated by TransitOps', 54, pageHeight - 32);
    pdf.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 100, pageHeight - 32);
  };

  // Title
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  doc.text(data.title, 54, currentY);
  currentY += 20;

  // Metadata
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  const genTime = new Date().toLocaleString();
  doc.text(`Generated on: ${genTime}`, 54, currentY);
  currentY += 25;

  // 3. KPIs
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Dashboard Summary', 54, currentY);
  currentY += 12;

  const kpisList = Object.entries(data.kpis);
  const cardWidth = (pageWidth - 108 - 30) / 4;
  const cardHeight = 45;

  for (let i = 0; i < kpisList.length; i += 4) {
    const chunk = kpisList.slice(i, i + 4);
    
    // Check page break before rendering cards row
    if (currentY + cardHeight + 20 > pageHeight - 60) {
      doc.addPage();
      currentY = 50;
    }
    
    chunk.forEach(([label, value], idx) => {
      const x = 54 + idx * (cardWidth + 10);
      doc.setFillColor(248, 250, 252);
      doc.rect(x, currentY, cardWidth, cardHeight, 'F');
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.rect(x, currentY, cardWidth, cardHeight, 'S');

      // Label
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(71, 85, 105);
      const cleanLabel = label.length > 25 ? label.slice(0, 22) + '...' : label;
      doc.text(cleanLabel.toUpperCase(), x + 6, currentY + 14);

      // Value
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(245, 158, 11);
      doc.text(String(value), x + 6, currentY + 34);
    });
    currentY += cardHeight + 10;
  }
  currentY += 10;

  // 4. Charts
  if (data.charts && data.charts.length > 0) {
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    
    if (currentY + 30 > pageHeight - 60) {
      doc.addPage();
      currentY = 50;
    }
    doc.text('Visual Analysis', 54, currentY);
    currentY += 15;

    for (let cIdx = 0; cIdx < data.charts.length; cIdx++) {
      const chart = data.charts[cIdx];
      if (currentY + 180 > pageHeight - 60) {
        doc.addPage();
        currentY = 50;
      }
      doc.addImage(chart, 'PNG', 54, currentY, pageWidth - 108, 160);
      currentY += 175;
    }
    currentY += 10;
  }

  // 5. Tables
  if (data.tables) {
    for (const [tableName, tableInfo] of Object.entries(data.tables)) {
      if (currentY + 50 > pageHeight - 60) {
        doc.addPage();
        currentY = 50;
      }

      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text(tableName, 54, currentY);
      currentY += 12;

      const colWidth = (pageWidth - 108) / tableInfo.headers.length;
      
      // Header fill
      doc.setFillColor(241, 245, 249);
      doc.rect(54, currentY, pageWidth - 108, 18, 'F');
      doc.setDrawColor(203, 213, 225);
      doc.line(54, currentY, pageWidth - 54, currentY);
      doc.line(54, currentY + 18, pageWidth - 54, currentY + 18);

      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(30, 41, 59);
      tableInfo.headers.forEach((h, hIdx) => {
        doc.text(h, 60 + hIdx * colWidth, currentY + 12);
      });
      currentY += 18;

      // Rows
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(51, 65, 85);
      tableInfo.rows.forEach((row, rIdx) => {
        if (currentY + 18 > pageHeight - 60) {
          doc.addPage();
          currentY = 50;
        }

        if (rIdx % 2 === 1) {
          doc.setFillColor(248, 250, 252);
          doc.rect(54, currentY, pageWidth - 108, 16, 'F');
        }
        
        row.forEach((cell, cellIdx) => {
          const strCell = String(cell);
          const cleanCell = strCell.length > 30 ? strCell.slice(0, 27) + '...' : strCell;
          doc.text(cleanCell, 60 + cellIdx * colWidth, currentY + 11);
        });

        doc.line(54, currentY + 16, pageWidth - 54, currentY + 16);
        currentY += 16;
      });
      currentY += 15;
    }
  }

  // Add header & footer to all pages
  const totalPages = doc.internal.getNumberOfPages();
  for (let pNum = 1; pNum <= totalPages; pNum++) {
    doc.setPage(pNum);
    drawPageDecorations(doc, pNum, totalPages);
  }

  doc.save(`transitops_report_${new Date().toISOString().slice(0, 10)}.pdf`);
}
