from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
import io
import base64
from datetime import datetime
import logging

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas

from .. import models, auth
from ..database import get_db

logger = logging.getLogger("transitops.reports")

router = APIRouter(prefix="/reports", tags=["reports"])

# ─── Pydantic schemas for request validation ──────────────────
class TableData(BaseModel):
    headers: List[str]
    rows: List[List[Any]]

class PDFExportRequest(BaseModel):
    title: str = Field(..., max_length=150)
    kpis: Dict[str, Any]
    charts: Optional[List[str]] = None  # Base64 data URLs
    tables: Optional[Dict[str, TableData]] = None

# ─── Custom Canvas for two-pass Page Numbering & Footers ──────
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_elements(num_pages)
            super().showPage()
        super().save()

    def draw_page_elements(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#6B7280"))
        
        # Header (Only on page 2 and later, or all pages)
        self.drawString(54, 800, "Fleet Analytics Report")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 792, 541, 792)
        
        # Footer
        self.line(54, 50, 541, 50)
        self.drawString(54, 38, "Generated by TransitOps")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(541, 38, page_text)
        self.restoreState()

@router.post("/export-pdf")
def export_pdf(
    payload: PDFExportRequest,
    current_user: models.User = Depends(auth.get_current_user)
):
    # 1. Enforce Role check on backend
    if current_user.role.value not in ["fleet_manager", "financial_analyst"]:
        logger.warning(f"Unauthorized PDF export attempt by {current_user.email} (role: {current_user.role.value})")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Role not authorized to export PDF reports"
        )

    try:
        # Create output buffer
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=54,
            rightMargin=54,
            topMargin=72,
            bottomMargin=72
        )

        styles = getSampleStyleSheet()
        
        # Custom styles matching TransitOps branding
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=colors.HexColor("#0F172A"),
            spaceAfter=6
        )
        
        subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#475569"),
            spaceAfter=15
        )

        section_heading = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#0F172A"),
            spaceBefore=15,
            spaceAfter=8,
            keepWithNext=True
        )

        card_label_style = ParagraphStyle(
            'CardLabel',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#475569")
        )

        card_value_style = ParagraphStyle(
            'CardValue',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=16,
            textColor=colors.HexColor("#F59E0B")
        )

        cell_header_style = ParagraphStyle(
            'CellHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#1E293B")
        )

        cell_text_style = ParagraphStyle(
            'CellText',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#334155")
        )

        story = []

        # Document Header
        story.append(Paragraph(payload.title, title_style))
        gen_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        meta_text = f"Generated by {current_user.name} ({current_user.email}) | Date & Time: {gen_time}"
        story.append(Paragraph(meta_text, subtitle_style))
        story.append(Spacer(1, 10))

        # ─── KPIs Section ───
        story.append(Paragraph("Dashboard Summary", section_heading))
        
        kpi_data = []
        kpi_row = []
        for label, val in payload.kpis.items():
            cell_p = [
                Paragraph(label.upper(), card_label_style),
                Spacer(1, 3),
                Paragraph(str(val), card_value_style)
            ]
            kpi_row.append(cell_p)
            if len(kpi_row) == 4:
                kpi_data.append(kpi_row)
                kpi_row = []
        if kpi_row:
            while len(kpi_row) < 4:
                kpi_row.append([])
            kpi_data.append(kpi_row)

        kpi_table = Table(kpi_data, colWidths=[121]*4)
        kpi_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F8FAFC")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#E2E8F0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('TOPPADDING', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('LEFTPADDING', (0,0), (-1,-1), 10),
            ('RIGHTPADDING', (0,0), (-1,-1), 10),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(kpi_table)
        story.append(Spacer(1, 20))

        # ─── Charts Section ───
        if payload.charts and len(payload.charts) > 0:
            story.append(Paragraph("Visual Analysis", section_heading))
            for i, chart_b64 in enumerate(payload.charts):
                try:
                    if "," in chart_b64:
                        chart_b64 = chart_b64.split(",")[1]
                    img_bytes = base64.b64decode(chart_b64)
                    img_io = io.BytesIO(img_bytes)
                    img = Image(img_io, width=480, height=200)
                    img.hAlign = 'CENTER'
                    story.append(img)
                    story.append(Spacer(1, 15))
                except Exception as chart_err:
                    logger.error(f"Failed to embed chart {i}: {str(chart_err)}")

        # ─── Tables Section ───
        if payload.tables:
            for tab_name, tab_info in payload.tables.items():
                story.append(Paragraph(tab_name, section_heading))
                
                # Headers wrapped in Paragraph
                headers = [Paragraph(h, cell_header_style) for h in tab_info.headers]
                table_rows = [headers]
                
                # Column widths allocation (even spread)
                col_count = len(tab_info.headers)
                col_width = 484.0 / max(col_count, 1)
                
                for r in tab_info.rows:
                    row_cells = []
                    for val in r:
                        row_cells.append(Paragraph(str(val), cell_text_style))
                    table_rows.append(row_cells)

                t = Table(table_rows, colWidths=[col_width]*col_count)
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 5),
                    ('TOPPADDING', (0,0), (-1,-1), 5),
                    ('LEFTPADDING', (0,0), (-1,-1), 6),
                    ('RIGHTPADDING', (0,0), (-1,-1), 6),
                    ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
                    ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
                    ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#F8FAFC")]),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ]))
                story.append(t)
                story.append(Spacer(1, 15))

        # Build doc
        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        
        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=transitops_report_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"}
        )
    except Exception as e:
        logger.exception("Failed to generate PDF report")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate report: {str(e)}"
        )
